### ISSUE TITLE
How long did it take to train this model？

### ISSUE THREAD

**Issue by dengjl-hub** [CVMI-Lab/MarS3D#1]
Thank you for your great work. I will appreciate if you report the length of training time, which will help others decide whether they are able to follow this work since some researchers don't have enough resource to train a model.

**Comment by jUstin-crchang** [comment]
Thank you for your interest in our repository and for reaching out. We greatly appreciate your kind words. In our experiments, we conducted training using two NVIDIA RTX 3090 GPUs. Taking the SPVCNN backbone as an example, training for 50 epochs typically takes around 70 hours. However, it's important to note that training times may slightly vary due to hardware constraints. This duration is comparable to training times for baseline methods. We hope this information proves useful in assessing the feasibility of replicating our work, especially for researchers with varying resource availability. If you have any further questions or need additional details, please don't hesitate to ask. Thank you once again for your interest :)
